In [ ]:
!pwd

/content


In [ ]:
%cd drive/MyDrive/NN-bootcamp/

/content/drive/MyDrive/NN-bootcamp


In [ ]:
import torch

In [ ]:
a=torch.tensor([2,2,1])

In [ ]:
print(a.size())

torch.Size([3])


In [ ]:
b=torch.FloatTensor(([2,1,3,3],[2,1,3,3]))

In [ ]:
b.view(-1,1)

tensor([[2.],
        [1.],
        [3.],
        [3.],
        [2.],
        [1.],
        [3.],
        [3.]])

In [ ]:
torch.rand(2,3,4)

tensor([[[0.9814, 0.1571, 0.8392, 0.5430],
         [0.8824, 0.1722, 0.3081, 0.7741],
         [0.5519, 0.0323, 0.3026, 0.3188]],

        [[0.3649, 0.2832, 0.3706, 0.0508],
         [0.4672, 0.8890, 0.1604, 0.0606],
         [0.5446, 0.3244, 0.6152, 0.6667]]])

In [ ]:
import numpy as np
import torch

In [ ]:
a=torch.ones(4)

In [ ]:
b=a.numpy()

In [ ]:
b

array([1., 1., 1., 1.], dtype=float32)

In [ ]:
a

tensor([1., 1., 1., 1.])

In [ ]:
x=torch.tensor([1.,2.,3.],requires_grad=True)
y=torch.tensor([4.,5.,6.],requires_grad=True)

In [ ]:
z=x+y

In [ ]:
s=z.sum()

In [ ]:
s.backward()

In [ ]:
print(x.grad)

tensor([1., 1., 1.])


In [ ]:
prediction=torch.randn(4,5)

In [ ]:
label=torch.randn(4,5)

In [ ]:
prediction

tensor([[-0.8177, -1.4385,  0.3677, -0.8332,  0.5911],
        [ 0.4337,  1.1565,  0.3161, -0.5010,  0.7281],
        [ 0.1923, -0.3789, -2.3938, -0.3503,  1.3030],
        [ 0.7264, -0.1685, -0.4482,  0.1787,  2.7349]])

In [ ]:
label

tensor([[ 0.1100, -1.2207, -1.5645, -0.9232,  1.3196],
        [-0.6181, -0.8839, -1.5406,  1.0324, -0.7305],
        [ 2.5864,  1.6568,  0.9734,  0.4123,  0.7465],
        [-0.8662,  1.5487, -0.2983, -0.8533,  0.7949]])

In [ ]:
import torch.nn as nn

In [ ]:
mse=nn.MSELoss(reduction='sum')

In [ ]:
loss=mse(prediction,label)

In [ ]:
loss

tensor(50.8175)

In [42]:
#weight initiazlition

In [43]:
layer=nn.Linear(5,5)

In [44]:
layer.weight

Parameter containing:
tensor([[ 0.2006,  0.0042, -0.1775,  0.1701,  0.3205],
        [-0.0214, -0.2967,  0.1338, -0.2131, -0.1400],
        [ 0.2327,  0.3642,  0.3286, -0.2906, -0.0023],
        [ 0.0270,  0.2737, -0.0466, -0.4160,  0.4390],
        [ 0.1808, -0.0530,  0.1185,  0.2204, -0.2974]], requires_grad=True)

In [49]:
nn.init.normal_(layer.weight,mean=0.0,std=3)

Parameter containing:
tensor([[-0.4911,  2.2507, -3.0966,  0.1859, -1.5784],
        [ 1.1430, -2.7829,  0.1255,  4.5779,  0.1583],
        [ 1.8876, -4.1547, -4.7769, -0.3530,  2.1016],
        [ 4.8107,  7.1839,  1.2617, -4.6342,  1.0125],
        [ 7.2561, -1.0000,  2.4437,  3.8572, -0.3173]], requires_grad=True)

In [50]:
layer.bias

Parameter containing:
tensor([-0.3627,  0.4027,  0.1841, -0.2701,  0.2440], requires_grad=True)